documents:
  - id: SR3003-02FR
    equipe: AFDR
    urlPdf: /api/Document/Pdf/AFDR@SR3003-02FR
    urlSoumissionForm: /api/Document/Soumettre/AFDR@SR3003-02FR
    urlEnregistrementForm: /api/Document/Enregistrer/AFDR@SR3003-02FR
    urlTelechargementForm: /api/Document/Telecharger/AFDR@SR3003-02FR
    urlCss: /api/Document/Css/SR3003
    urlConfirmation: /Visionneuse/Confirmation/AFDR@SR3003-02FR
    ide: 0358
    modeTraitement: courriel
    courriels:
      - id: boiteGenerique
        a: ESUN-A01@ESSAIS.MESS.GOUV.QC.CA
        retourA: ESUN-A01@ESSAIS.MESS.GOUV.QC.CA
        de: ESUN-DE01@ESSAIS.MESS.GOUV.QC.CA
        objet: "DEMANDE no. {{ide}}"
        corps: "Comptes ?? : {{ComptesOuiC }} <br />  {{{raw}}}"
        nomPieceJointe: "{{ide}}.pdf"
        evenementAffaire: AFDR-SR3003
    Messages:
        - id: succes
          AfficherBoutonImpression: true
          Titre: "Demande transmise avec succès"
          Texte1: "Votre demande d'aide financière de dernier recours a été transmise avec succès."
          Texte2: "Le no de confirmation est : {NoConfirmation}"
          HtmlCustom: 
